import type {Metadata} from "next";
import {Poppins} from "next/font/google"
import "./globals.css";
import React from "react";
import {Toaster} from "@/components/ui/toaster";

const font = Poppins({subsets: ["latin"], weight: "400"})

export const metadata: Metadata = {
    title: "Velocity Crew Centre",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${font.className} dark antialiased`}>
                {children}
                <Toaster/>
            </body>
        </html>
    );
}
